-- =============================================================================
-- Migration: 20260305000031_create_monthly_invoices
--
-- Creates:
--   type  public.invoice_status      enum for monthly invoice lifecycle
--   table public.monthly_invoices    compiled monthly financial statement
--   RLS   monthly_invoices           admin write; admin read
-- =============================================================================

-- ─── Enum: invoice_status ────────────────────────────────────────────────────
-- Lifecycle of a monthly invoice from computation through archival.
--
-- SYNC REQUIREMENT: values must match @gtg/types InvoiceStatus exactly.

create type public.invoice_status as enum (
  'draft',      -- Computed; pending admin review before action
  'finalized',  -- Locked; commission payouts and licensor submissions may proceed
  'voided'      -- Invalidated; a corrected restatement must be issued separately
);

-- ─── Table: monthly_invoices ──────────────────────────────────────────────────
-- One row per calendar month — the master financial document for that period.
-- Captures scalar aggregates for fast reporting and full JSONB snapshots for
-- display and audit. Generated by the compile-monthly-invoice / generate-invoice-
-- record pipeline (3E-4).
--
-- Scalar columns:
--   Revenue, commission, and royalty figures are stored as first-class bigint
--   columns for direct SQL aggregation (e.g. YTD totals, trend queries) without
--   parsing JSONB. bigint is used (not integer) because monthly aggregates can
--   exceed 2 147 483 647 cents (~$21M) on a busy platform.
--
-- JSONB snapshots:
--   revenue_snapshot    — full revenue section including by_license_body[]
--   commissions_snapshot — full commissions section including per-consultant arrays
--   royalties_snapshot  — array of per-licensor royalty obligation objects
--
--   Snapshots are the authoritative detail record. Scalar columns are derived
--   from snapshots at insert time and must not be edited independently.
--
-- Immutability contract:
--   'draft' invoices may be regenerated (voided + new insert) before any
--   downstream action (payout, licensor submission) has been taken.
--   Once status reaches 'finalized', the invoice is locked. Corrections
--   require voiding this record and issuing a new one.
--   Hard delete is prohibited.

create table public.monthly_invoices (

  -- ── Identity ────────────────────────────────────────────────────────────────
  id                               uuid           not null  default gen_random_uuid(),

  -- 'YYYY-MM' — human-readable display key and URL-safe lookup handle.
  -- Redundant with period_start but kept for application convenience.
  year_month                       text           not null,

  -- Period boundaries (inclusive on both ends, derived from year_month at insert).
  period_start                     date           not null,
  period_end                       date           not null,

  -- ── Revenue scalars (from calculate_gross_month) ────────────────────────────
  gross_sales_cents                bigint         not null,
  returns_cents                    bigint         not null,
  net_sales_cents                  bigint         not null,

  -- ── Commission scalars (from calculate_gross_month) ─────────────────────────
  -- gross_accrued_cents: all commissions created in the period (any status)
  gross_accrued_cents              bigint         not null,
  -- reversals_this_period_cents: commissions reversed by reversed_at in period
  reversals_this_period_cents      bigint         not null,
  -- net_commission_cents: gross_accrued − reversals (may be negative)
  net_commission_cents             bigint         not null,
  -- approved_payable_cents: commissions with status = 'approved' created this period
  approved_payable_cents           bigint         not null,
  -- held_cents: commissions with status = 'held' created this period
  held_cents                       bigint         not null,

  -- ── Royalty scalars (aggregated across all licensors) ────────────────────────
  -- Sum of remittance_cents across all royalty obligations for the period.
  -- Each licensor's remittance applies the GREATEST(royalty_cents, minimum) floor.
  total_royalties_remittance_cents bigint         not null,

  -- ── Derived platform position ────────────────────────────────────────────────
  -- net_platform_cents = net_sales − total_royalties_remittance − net_commission
  -- May be negative; signals clawback period or high-return activity.
  net_platform_cents               bigint         not null,

  -- ── Full JSONB snapshots ─────────────────────────────────────────────────────
  -- Authoritative detail for display, audit, and licensor submissions.
  -- Scalar columns above are derived from these snapshots at insert time.
  revenue_snapshot                 jsonb          not null,
  commissions_snapshot             jsonb          not null,
  royalties_snapshot               jsonb          not null,   -- array of per-licensor objects

  -- ── Lifecycle ────────────────────────────────────────────────────────────────
  status                           public.invoice_status  not null  default 'draft',

  finalized_at                     timestamptz,
  finalized_by                     uuid           references auth.users (id),

  void_reason                      text,
  voided_at                        timestamptz,
  voided_by                        uuid           references auth.users (id),

  -- ── Audit ────────────────────────────────────────────────────────────────────
  created_at                       timestamptz    not null  default now(),
  created_by                       uuid           not null  references auth.users (id),
  updated_at                       timestamptz    not null  default now(),

  -- ── Constraints ──────────────────────────────────────────────────────────────

  constraint monthly_invoices_pkey
    primary key (id),

  -- One invoice per calendar month. Voided invoices hold the slot —
  -- a corrected restatement for the same period requires admin review.
  constraint monthly_invoices_period_unique
    unique (period_start, period_end),

  constraint monthly_invoices_period_ordered
    check (period_end >= period_start),

  constraint monthly_invoices_year_month_format
    check (year_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),

  -- Revenue constraints
  constraint monthly_invoices_gross_sales_nonneg
    check (gross_sales_cents >= 0),

  constraint monthly_invoices_returns_nonneg
    check (returns_cents >= 0),

  -- net_sales_cents may be negative in pathological cases (returns > sales)
  -- but is not constrained — the value is informational.

  -- Commission constraints
  constraint monthly_invoices_gross_accrued_nonneg
    check (gross_accrued_cents >= 0),

  constraint monthly_invoices_reversals_nonneg
    check (reversals_this_period_cents >= 0),

  -- net_commission_cents may be negative — documented in the DB function comment.

  constraint monthly_invoices_approved_payable_nonneg
    check (approved_payable_cents >= 0),

  constraint monthly_invoices_held_nonneg
    check (held_cents >= 0),

  -- Royalty constraint
  constraint monthly_invoices_total_royalties_nonneg
    check (total_royalties_remittance_cents >= 0),

  -- Lifecycle consistency
  constraint monthly_invoices_finalization_consistent
    check (
      (finalized_at is null and finalized_by is null)
      or
      (finalized_at is not null and finalized_by is not null)
    ),

  constraint monthly_invoices_void_consistent
    check (
      (voided_at is null and voided_by is null and void_reason is null)
      or
      (voided_at is not null and voided_by is not null and void_reason is not null)
    )
);

-- ─── updated_at Trigger ───────────────────────────────────────────────────────

create trigger monthly_invoices_set_updated_at
  before update on public.monthly_invoices
  for each row
  execute function public.set_updated_at();

-- ─── Indexes ─────────────────────────────────────────────────────────────────

-- Status filter: find all draft invoices pending finalization.
create index monthly_invoices_status_idx
  on public.monthly_invoices (status);

-- Chronological browse: most recent period first.
create index monthly_invoices_period_start_desc_idx
  on public.monthly_invoices (period_start desc);

-- ─── Row Level Security ───────────────────────────────────────────────────────

alter table public.monthly_invoices enable row level security;

-- SELECT: admins only. Monthly invoices are the master financial document —
-- consultant-facing and auditor-facing reporting draws from derived views,
-- not from the raw invoice table.
create policy "monthly_invoices_select_admin"
  on public.monthly_invoices
  for select
  to authenticated
  using (
    (auth.jwt() -> 'app_metadata' ->> 'role') in ('admin', 'super_admin')
  );

-- INSERT: admin only. Created exclusively by the generate-invoice-record function.
create policy "monthly_invoices_insert_admin"
  on public.monthly_invoices
  for insert
  to authenticated
  with check (
    (auth.jwt() -> 'app_metadata' ->> 'role') in ('admin', 'super_admin')
  );

-- UPDATE: admin only. Status transitions (finalize, void) only.
create policy "monthly_invoices_update_admin"
  on public.monthly_invoices
  for update
  to authenticated
  using (
    (auth.jwt() -> 'app_metadata' ->> 'role') in ('admin', 'super_admin')
  )
  with check (
    (auth.jwt() -> 'app_metadata' ->> 'role') in ('admin', 'super_admin')
  );

-- DELETE: prohibited. Void with status = 'voided'.

-- ─── Column Documentation ─────────────────────────────────────────────────────

comment on table public.monthly_invoices is
  'Master monthly financial document — one row per calendar month. '
  'Stores scalar aggregates for fast SQL reporting and full JSONB snapshots '
  'for display and audit. Generated by the generate-invoice-record pipeline '
  'step (3E-4). Immutable once finalized; corrections require voiding and '
  'issuing a corrected restatement.';

comment on column public.monthly_invoices.year_month is
  'Human-readable month key in YYYY-MM format. Redundant with period_start '
  'but kept for application convenience and URL routing.';

comment on column public.monthly_invoices.net_commission_cents is
  'gross_accrued_cents minus reversals_this_period_cents. May be negative '
  'in high-return or clawback periods. Downstream payout logic must handle negative values.';

comment on column public.monthly_invoices.net_platform_cents is
  'Approximated platform net before operator expenses: '
  'net_sales_cents − total_royalties_remittance_cents − net_commission_cents. '
  'May be negative. Informational — does not account for overhead costs.';

comment on column public.monthly_invoices.revenue_snapshot is
  'Full revenue section from calculate_gross_month: gross_sales_cents, '
  'returns_cents, net_sales_cents, and by_license_body[] breakdown.';

comment on column public.monthly_invoices.commissions_snapshot is
  'Full commissions section from calculate_gross_month: accrued, reversed, '
  'net, payable, held totals, plus by_consultant_accrued[] and '
  'by_consultant_reversals[] arrays.';

comment on column public.monthly_invoices.royalties_snapshot is
  'Array of per-licensor royalty obligation objects from calculate_royalties_month. '
  'Each entry carries units_sold, gross_sales_cents, royalty_cents, '
  'remittance_cents, rate_groups[], and the full ledger_entry_ids audit chain.';
